@extends('layouts.app')
@section('title', 'Novo lançamento')
@section('content')
<a class="back-link" href="{{ route('finance.index') }}">← Voltar ao financeiro</a><div class="page-heading"><div><span class="eyebrow">MOVIMENTAÇÃO DE CAIXA</span><h1>Novo lançamento</h1><p class="muted">Registre um valor que já entrou ou saiu da gráfica.</p></div></div>
<form class="finance-form" method="POST" action="{{ route('finance.store') }}">@csrf @include('partials.errors')<section class="card"><div class="section-heading"><div><h2>Dados da movimentação</h2><p class="muted">Os campos marcados com <span class="required">*</span> são obrigatórios.</p></div></div><div class="form-body">
<fieldset class="entry-type"><legend>Tipo de movimentação <span class="required" aria-hidden="true">*</span></legend><div class="entry-type-options"><label><input type="radio" name="type" value="income" @checked(old('type', 'income') === 'income') required><span class="entry-type-card"><x-icon name="arrow-down"/>Entrada de dinheiro</span></label><label><input type="radio" name="type" value="expense" @checked(old('type') === 'expense') required><span class="entry-type-card"><x-icon name="arrow"/>Saída de dinheiro</span></label></div>@error('type')<p class="field-error">{{ $message }}</p>@enderror</fieldset>
<div class="form-grid"><div class="field"><label for="description">Descrição <span class="required" aria-hidden="true">*</span></label><input id="description" name="description" value="{{ old('description') }}" maxlength="255" required autocomplete="off" placeholder="Ex.: compra de papel"><p class="field-hint">Use um nome fácil de reconhecer no extrato.</p>@error('description')<p class="field-error">{{ $message }}</p>@enderror</div><div class="field"><label for="category">Categoria</label><input id="category" name="category" value="{{ old('category') }}" maxlength="100" placeholder="Ex.: materiais"><p class="field-hint">Você pode criar a categoria que fizer sentido para sua equipe.</p>@error('category')<p class="field-error">{{ $message }}</p>@enderror</div></div>
<div class="form-grid"><div class="field"><label for="amount">Valor <span class="required" aria-hidden="true">*</span></label><div class="money-input"><span aria-hidden="true">R$</span><input id="amount" name="amount" type="text" inputmode="decimal" autocomplete="off" data-money-input value="{{ old('amount') }}" placeholder="0,00" aria-describedby="amount-hint{{ $errors->has('amount') ? ' amount-error' : '' }}" required @error('amount') aria-invalid="true" @enderror></div><p id="amount-hint" class="field-hint">Digite o valor em reais. O campo organiza centavos e separadores automaticamente.</p>@error('amount')<p class="field-error" id="amount-error">{{ $message }}</p>@enderror</div><div class="field"><label for="occurred_on">Data <span class="required" aria-hidden="true">*</span></label><input id="occurred_on" name="occurred_on" type="date" max="{{ now()->format('Y-m-d') }}" value="{{ old('occurred_on', now()->format('Y-m-d')) }}" required>@error('occurred_on')<p class="field-error">{{ $message }}</p>@enderror</div></div>
<div class="field"><label for="payment_method">Forma de pagamento</label><select id="payment_method" name="payment_method"><option value="">Selecione, se desejar</option>@foreach(['pix' => 'Pix', 'cash' => 'Dinheiro', 'debit' => 'Cartão de débito', 'credit' => 'Cartão de crédito', 'transfer' => 'Transferência', 'other' => 'Outra'] as $value => $label)<option value="{{ $value }}" @selected(old('payment_method') === $value)>{{ $label }}</option>@endforeach</select>@error('payment_method')<p class="field-error">{{ $message }}</p>@enderror</div>
<div class="field"><label for="notes">Observações</label><textarea id="notes" name="notes" rows="3" maxlength="5000" placeholder="Detalhes opcionais">{{ old('notes') }}</textarea>@error('notes')<p class="field-error">{{ $message }}</p>@enderror</div>
</div><div class="form-actions"><a class="button secondary" href="{{ route('finance.index') }}">Cancelar</a><button class="button primary" type="submit">Salvar lançamento</button></div></section></form>
@endsection
