@extends('layouts.app')
@section('title', 'Financeiro')
@section('content')
<div class="page-heading"><div><span class="eyebrow">CONTROLE DA GRÁFICA</span><h1>Financeiro</h1><p class="muted">Acompanhe o que entrou e saiu do caixa.</p></div><a class="button primary" href="{{ route('finance.create') }}"><x-icon name="plus"/>Novo lançamento</a></div>
@include('partials.errors')
<form class="card finance-filters" method="GET" action="{{ route('finance.index') }}"><div class="field"><label for="month">Mês de referência</label><input id="month" name="month" type="month" value="{{ $month }}"></div><div class="field"><label for="type">Tipo de lançamento</label><select id="type" name="type"><option value="all" @selected($type === 'all')>Entradas e saídas</option><option value="income" @selected($type === 'income')>Somente entradas</option><option value="expense" @selected($type === 'expense')>Somente saídas</option></select></div><button class="button secondary" type="submit">Atualizar período</button></form>
<section class="finance-summary" aria-label="Resumo do mês"><article class="card finance-stat income-stat"><span class="eyebrow">ENTRADAS</span><strong>{{ $incomeLabel }}</strong><span class="muted">No mês selecionado</span></article><article class="card finance-stat expense-stat"><span class="eyebrow">SAÍDAS</span><strong>{{ $expenseLabel }}</strong><span class="muted">No mês selecionado</span></article><article class="card finance-stat balance-stat"><span class="eyebrow">SALDO DO PERÍODO</span><strong>{{ $balanceLabel }}</strong><span class="muted">Entradas menos saídas registradas</span></article></section>
<section class="card finance-chart" aria-labelledby="cash-chart-title"><div class="section-heading"><div><span class="eyebrow">MOVIMENTO REAL</span><h2 id="cash-chart-title">Seis meses até o período selecionado</h2><p class="muted">Comparativo mensal de entradas e saídas registradas.</p></div><div class="chart-legend"><span><i class="legend-dot income-dot"></i>Entradas</span><span><i class="legend-dot expense-dot"></i>Saídas</span></div></div>
<div class="bar-chart" role="list" aria-label="Entradas e saídas dos últimos seis meses">@foreach($chart as $item)@php($incomeHeight = $item['income'] > 0 ? max(3, (int) round($item['income'] / $chartMax * 100)) : 0)@php($expenseHeight = $item['expense'] > 0 ? max(3, (int) round($item['expense'] / $chartMax * 100)) : 0)<div class="chart-month" role="listitem"><span class="sr-only">{{ $item['label'] }}: entradas {{ $item['income_label'] }}, saídas {{ $item['expense_label'] }}</span><div class="chart-bars" aria-hidden="true"><div class="chart-bar income-bar" style="height:{{ $incomeHeight }}%"></div><div class="chart-bar expense-bar" style="height:{{ $expenseHeight }}%"></div></div><span aria-hidden="true">{{ $item['label'] }}</span></div>@endforeach</div>
</section>
<section class="card finance-ledger" aria-labelledby="entries-title"><div class="section-heading"><div><h2 id="entries-title">Lançamentos</h2><p class="muted">{{ $entries->total() }} registro(s) no período e filtro selecionados.</p></div></div>
@if($entries->isEmpty())<div class="empty-state"><span class="empty-icon"><x-icon name="chart"/></span><h3>Nenhum lançamento neste período</h3><p>Registre uma entrada ou saída para começar a acompanhar o caixa da sua gráfica.</p><a class="button secondary" href="{{ route('finance.create') }}">Registrar lançamento</a></div>
@else<div class="table-scroll"><table><caption class="sr-only">Lançamentos financeiros do mês</caption><thead><tr><th scope="col">Descrição</th><th scope="col">Categoria</th><th scope="col">Data</th><th scope="col">Tipo</th><th scope="col" class="text-right">Valor</th></tr></thead><tbody>@foreach($entries as $entry)<tr><td><strong>{{ $entry->description }}</strong>@if($entry->notes)<span class="table-subtitle">{{ $entry->notes }}</span>@endif</td><td>{{ $entry->category ?: '—' }}</td><td>{{ $entry->occurred_on->format('d/m/Y') }}</td><td><span @class(['badge', 'ledger-income' => $entry->type === 'income', 'ledger-expense' => $entry->type === 'expense'])>{{ $entry->type === 'income' ? 'Entrada' : 'Saída' }}</span></td><td @class(['text-right','amount-income' => $entry->type === 'income','amount-expense' => $entry->type === 'expense'])>{{ $entry->type === 'income' ? '+' : '−' }} {{ $entry->formatted_amount }}</td></tr>@endforeach</tbody></table></div>{{ $entries->withQueryString()->links('partials.pagination', ['paginationLabel' => 'Paginação de lançamentos']) }}@endif
</section>
<p class="finance-note">Este painel registra movimentações informadas pela equipe. Contas a pagar e receber, conciliação e integração com pedidos serão adicionadas em etapas futuras.</p>
@endsection
