@include('partials.errors')
@php($unitLabels = ['unit' => 'Unidade', 'linear_meter' => 'Metro linear', 'square_meter' => 'Metro quadrado', 'lot' => 'Lote', 'custom' => 'Personalizada'])
<div class="card"><div class="section-heading"><div><h2>Dados do produto</h2><p class="muted">Campos com <span class="required">*</span> são obrigatórios.</p></div></div><div class="form-body">
<x-field name="name" label="Nome do produto" :value="$product->name ?? ''" :required="true" maxlength="255"/>
<div class="form-grid"><x-field name="category" label="Categoria (opcional)" :value="$product->category ?? ''" maxlength="255"/><x-field name="sku" label="Código / SKU (opcional)" :value="$product->sku ?? ''" maxlength="255"/></div>
<div class="field"><label for="description">Descrição (opcional)</label><textarea id="description" name="description" rows="4" @error('description') aria-invalid="true" aria-describedby="description-error" @enderror>{{ old('description', $product->description ?? '') }}</textarea>@error('description')<p class="field-error" id="description-error">{{ $message }}</p>@enderror</div>
<div class="form-grid"><div class="field"><label for="unit">Unidade de venda <span class="required" aria-hidden="true">*</span></label><select id="unit" name="unit" required @error('unit') aria-invalid="true" aria-describedby="unit-error" @enderror>@foreach($unitLabels as $value => $label)<option value="{{ $value }}" @selected(old('unit', $product->unit ?? 'unit') === $value)>{{ $label }}</option>@endforeach</select>@error('unit')<p class="field-error" id="unit-error">{{ $message }}</p>@enderror</div>
<div data-custom-unit><x-field name="unit_label" label="Nome da unidade personalizada" :value="$product->unit_label ?? ''" maxlength="255" aria-describedby="unit-label-hint"/><p class="field-hint" id="unit-label-hint">Preencha somente ao selecionar a unidade Personalizada.</p></div></div>
<div class="field"><label for="price">Preço por unidade de venda (R$, opcional)</label><p class="field-hint" id="price-hint">Deixe em branco se ainda não houver preço definido. Informe um valor sem separador de milhar, como 12,50. Este cadastro não calcula custos, quantidades ou orçamento.</p><input id="price" name="price" type="text" inputmode="decimal" value="{{ old('price', $product->price ?? '') }}" aria-describedby="price-hint{{ $errors->has('price') ? ' price-error' : '' }}" @error('price') aria-invalid="true" @enderror>@error('price')<p class="field-error" id="price-error">{{ $message }}</p>@enderror</div>
<input type="hidden" name="is_active" value="0"><label class="checkbox catalog-checkbox" for="is_active"><input type="checkbox" id="is_active" name="is_active" value="1" @checked(old('is_active', $product->is_active ?? true)) @error('is_active') aria-invalid="true" aria-describedby="is-active-error" @enderror>Produto ativo</label>@error('is_active')<p class="field-error" id="is-active-error">{{ $message }}</p>@enderror
</div><div class="form-actions"><a class="button secondary" href="{{ isset($product) && $product->exists ? route('products.show', $product) : route('products.index') }}">Cancelar</a><button class="button primary" type="submit">{{ isset($product) && $product->exists ? 'Salvar alterações' : 'Cadastrar produto' }}</button></div></div>
