@extends('layouts.app')
@section('title', 'Catálogo')
@section('content')
@php($unitLabels = ['unit' => 'Unidade', 'linear_meter' => 'Metro linear', 'square_meter' => 'Metro quadrado', 'lot' => 'Lote', 'custom' => 'Personalizada'])
<div class="page-heading"><div><span class="eyebrow">PRODUTOS DA SUA GRÁFICA</span><h1>Catálogo</h1><p class="muted">Organize o que você produz, com unidades e preços claros.</p></div><a class="button primary" href="{{ route('products.create') }}"><x-icon name="plus"/>Novo produto</a></div>
@include('partials.errors')
<div class="catalog-overview"><div class="card catalog-total"><span class="eyebrow">{{ ($search !== '' || $status !== 'all') ? 'RESULTADOS DOS FILTROS' : 'PRODUTOS CADASTRADOS' }}</span><strong>{{ $products->total() }}</strong><span class="muted">{{ $products->total() === 1 ? 'produto' : 'produtos' }}</span></div><div class="catalog-intro"><h2>Cada produto, do seu jeito.</h2><p>Defina a unidade de venda de cada item. O preço é opcional e pode ser preenchido quando você tiver essa informação.</p></div></div>
<section class="card" aria-labelledby="catalog-title"><div class="section-heading"><div><h2 id="catalog-title">Seus produtos</h2><p class="muted">Busque um produto ou filtre pela situação do cadastro.</p></div></div>
<form class="catalog-filters" method="GET" action="{{ route('products.index') }}"><div class="field"><label for="q">Buscar produto</label><input id="q" name="q" type="search" maxlength="255" value="{{ $search }}" placeholder="Digite sua busca"></div><div class="field"><label for="status">Situação</label><select id="status" name="status"><option value="all" @selected($status === 'all')>Todos</option><option value="active" @selected($status === 'active')>Ativos</option><option value="inactive" @selected($status === 'inactive')>Inativos</option></select></div><button class="button secondary" type="submit"><x-icon name="search"/>Filtrar</button>@if($search !== '' || $status !== 'all')<a class="text-link" href="{{ route('products.index') }}">Limpar filtros</a>@endif</form>
@if($products->isEmpty())
<div class="empty-state"><span class="empty-icon"><x-icon name="catalog"/></span><h3>{{ ($search !== '' || $status !== 'all' || $products->total() > 0) ? 'Nenhum produto nesta seleção' : 'Seu catálogo começa aqui' }}</h3><p>{{ ($search !== '' || $status !== 'all' || $products->total() > 0) ? 'Ajuste os filtros ou volte para a primeira página para encontrar seus produtos.' : 'Cadastre o primeiro produto da sua gráfica e reúna as informações para o atendimento.' }}</p>@if($search !== '' || $status !== 'all' || $products->total() > 0)<a class="button secondary" href="{{ route('products.index') }}">Ver catálogo completo</a>@else<a class="button secondary" href="{{ route('products.create') }}">Cadastrar primeiro produto</a>@endif</div>
@else
<div class="catalog-grid">@foreach($products as $product)<article class="catalog-product"><div class="catalog-product-top"><span class="catalog-symbol"><x-icon name="catalog"/></span><span @class(['badge', 'status-active' => $product->is_active])>{{ $product->is_active ? 'Ativo' : 'Inativo' }}</span></div><h3><a href="{{ route('products.show', $product) }}">{{ $product->name }}</a></h3><p class="muted catalog-category">{{ $product->category ?: 'Sem categoria' }}</p><dl class="catalog-facts"><div><dt>Unidade de venda</dt><dd>{{ $product->unit === 'custom' ? $product->unit_label : ($unitLabels[$product->unit] ?? $product->unit) }}</dd></div><div><dt>Preço cadastrado</dt><dd>{{ $product->price_cents === null ? 'Não informado' : 'R$ '.number_format($product->price_cents / 100, 2, ',', '.') }}</dd></div></dl><a class="text-link" href="{{ route('products.show', $product) }}" aria-label="Ver produto {{ $product->name }}">Ver produto<x-icon name="arrow"/></a></article>@endforeach</div>
@endif
{{ $products->withQueryString()->links('partials.pagination', ['paginationLabel' => 'Paginação de produtos']) }}
</section>
@endsection
