@extends('layouts.app')
@section('title', $product->name)
@section('content')
@php($unitLabels = ['unit' => 'Unidade', 'linear_meter' => 'Metro linear', 'square_meter' => 'Metro quadrado', 'lot' => 'Lote', 'custom' => 'Personalizada'])
<a class="back-link" href="{{ route('products.index') }}">← Voltar para catálogo</a><div class="page-heading"><div><span class="eyebrow">CATÁLOGO</span><h1>{{ $product->name }}</h1><span @class(['badge', 'status-active' => $product->is_active])>{{ $product->is_active ? 'Ativo' : 'Inativo' }}</span></div><a class="button primary" href="{{ route('products.edit', $product) }}">Editar produto</a></div>
@include('partials.errors')
<section class="card" aria-labelledby="product-details"><div class="section-heading"><h2 id="product-details">Informações do produto</h2></div><dl class="detail-grid"><div><dt>Categoria</dt><dd>{{ $product->category ?: 'Não informada' }}</dd></div><div><dt>Código / SKU</dt><dd>{{ $product->sku ?: 'Não informado' }}</dd></div><div><dt>Unidade de venda</dt><dd>{{ $product->unit === 'custom' ? $product->unit_label : ($unitLabels[$product->unit] ?? $product->unit) }}</dd></div><div><dt>Preço por unidade de venda</dt><dd>{{ $product->price_cents === null ? 'Não informado' : 'R$ '.number_format($product->price_cents / 100, 2, ',', '.') }}</dd></div></dl><div class="notes-section"><h3>Descrição</h3><p class="notes">{{ $product->description ?: 'Nenhuma descrição cadastrada.' }}</p></div></section>
<section class="card catalog-status" aria-labelledby="status-title"><h2 id="status-title">{{ $product->is_active ? 'Desativar produto' : 'Reativar produto' }}</h2><p class="muted">{{ $product->is_active ? 'O produto ficará identificado como inativo. Os dados do cadastro serão preservados.' : 'O produto voltará a ser identificado como ativo no catálogo.' }}</p>
{{-- Confirmação explícita funciona por teclado e sem depender de JavaScript. --}}
<form method="POST" action="{{ route('products.toggle', $product) }}">@csrf @method('PATCH')<input type="hidden" name="is_active" value="{{ $product->is_active ? 0 : 1 }}"><label class="checkbox catalog-checkbox" for="confirm-status"><input type="checkbox" id="confirm-status" required>Confirmo que desejo {{ $product->is_active ? 'desativar' : 'reativar' }} este produto.</label><button class="button secondary" type="submit">{{ $product->is_active ? 'Desativar produto' : 'Reativar produto' }}</button></form></section>
@endsection
